version: '5'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 3000:3000
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      - FINN_HUB_API_KEY=***REMOVED***
      - ALPHA_VANTAGE_API_KEY=***REMOVED***

      - MONGO_SERVER_URL=database
      - MONGO_BACKUP_URL=***REMOVED***

      - REDIS_SERVER_URL=cache
    ports:
      - 8000:8000
    depends_on:
      - database
      - cache
      - search
  cache:
    container_name: cache
    image: redis:alpine
    restart: always
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    logging:
      driver: "none"
  search:
    container_name: search
    build:
      context: ./search
      dockerfile: Dockerfile
    restart: always
    