version: '5'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - FINN_HUB_API_KEY = "***REMOVED***"
      - ALPHA_VANTAGE_API_KEY = "***REMOVED***"

      - MONGO_SERVER_URL = "database"
      - MONGO_BACKUP_URL = "***REMOVED***"

      - REDIS_SERVER_URL = "cache"

      - MEILISEARCH_SERVER_URL = "search"
      - MEILISEARCH_MASTER_KEY = "***REMOVED***"
    depends_on:
      - cache
      - database
      - search
    restart: always
  cache:
    container_name: cache
    image: redis:alpine
    restart: always
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    logging:
      driver: "none"
    volumes:
      - ./database/data.mongo:/data/db
    restart: always
  search:
    container_name: search
    build:
      context: ./search
      dockerfile: Dockerfile
    volumes:
      - ./search/data.ms:/data/data.ms
    restart: always
    