services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      - FINN_HUB_API_KEY=${FINN_HUB_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - OPEN_FIGI_API_KEY=${OPEN_FIGI_API_KEY}

      - MONGO_SERVER_URL=${MONGO_SERVER_URL}
      - MONGO_BACKUP_URL=${MONGO_BACKUP_URL}

      - REDIS_SERVER_URL=${REDIS_SERVER_URL}

      - MEILISEARCH_SERVER_URL=${MEILISEARCH_SERVER_URL}
      - MEILISEARCH_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
    networks:
      - staging
    depends_on:
      - database
      - cache
      - search
  cache:
    container_name: cache
    build:
      context: ./backend/cache
      dockerfile: Dockerfile
    restart: always
    networks:
      - staging
  database:
    container_name: database
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    restart: always
    networks:
      - staging
  search:
    container_name: search
    build:
      context: ./backend/search
      dockerfile: Dockerfile
    restart: always
    networks:
      - staging

  proxy:
    container_name: proxy
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 81:81
      - 443:443
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
    networks:
      - staging
    depends_on:
      - backend

networks:
  staging:
    driver: bridge
