services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - "production.env"
    networks:
      - staging
    depends_on:
      - database
      - cache
      - search
  cache:
    container_name: cache
    build:
      context: ./backend/cache
      dockerfile: Dockerfile
    volumes:
      - /data.redis:/data
    restart: always
    networks:
      - staging
  database:
    container_name: database
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    volumes:
      - /data.mongo:/data/db
    restart: always
    networks:
      - staging
  search:
    container_name: search
    build:
      context: ./backend/search
      dockerfile: Dockerfile
    # volumes:
    #   - /data.ms:/data/data.ms
    restart: always
    networks:
      - staging

  proxy:
    container_name: proxy
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 81:81
      - 443:443
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
    networks:
      - staging
    depends_on:
      - backend

networks:
  staging:
    driver: bridge