services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - BACKEND_SERVER_URL=http://***REMOVED***:8000
    volumes:
      - ./frontend/pages:/app/pages
      - ./frontend/public:/app/public
      - ./frontend/components:/app/components
      - ./frontend/styles:/app/styles
      - ./frontend/redux:/app/redux
    ports:
      - 3000:3000
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - FINN_HUB_API_KEY=***REMOVED***
      - ALPHA_VANTAGE_API_KEY=***REMOVED***

      - MONGO_SERVER_URL=mongodb://database
      - MONGO_BACKUP_URL=***REMOVED***

      - REDIS_SERVER_URL=cache

      - MEILISEARCH_SERVER_URL=http://search:7700
      - MEILISEARCH_MASTER_KEY=***REMOVED***
    volumes:
      - ./backend/routers:/code/routers
    ports:
      - 8000:8000
    depends_on:
      - database
      - cache
      - search
  cache:
    container_name: cache
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    logging:
      driver: "none"
    ports:
      - 27017:27017
  search:
    container_name: search
    build:
      context: ./search
      dockerfile: Dockerfile
    volumes:
      - ./search/data.ms:/data/data.ms
    restart: always
    ports:
      - 7700:7700
