version: "5.6"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - BACKEND_SERVER_URL=${BACKEND_SERVER_URL}
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - FINN_HUB_API_KEY=${FINN_HUB_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}

      - MONGO_SERVER_URL=${MONGO_SERVER_URL}
      - MONGO_BACKUP_URL=${MONGO_BACKUP_URL}

      - REDIS_SERVER_URL=${REDIS_SERVER_URL}

      - MEILISEARCH_SERVER_URL=${MEILISEARCH_SERVER_URL}
      - MEILISEARCH_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
    depends_on:
      - cache
      - database
      - search
    restart: always
  cache:
    container_name: cache
    image: redis:alpine
    restart: always
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    logging:
      driver: "none"
    volumes:
      - ./database/data.mongo:/data/db
    restart: always
  search:
    container_name: search
    build:
      context: ./search
      dockerfile: Dockerfile
    volumes:
      - ./search/data.ms:/data/data.ms
    restart: always
