name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SECRETS_URL: ${{ secrets.SECRETS_URL }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          url: ${{ secrets.ENV_URL }}
          script: |
            cd server
            curl "$url" > docker-compose.prod.yaml
            bash deploy.sh
